// for add to cart
const ADD_CART = "ADD_CART"
const ADD_CART_RED = "ADD_CART_RED"
const GET_CART = "ADD_CART"
const GET_CART_RED = "ADD_CART_RED"
const UPDATE_CART = "UPDATE_CART"
const UPDATE_CART_RED = "UPDATE_CART_RED"
const  DELETE_CART = " DELETE_CART"
const  DELETE_CART_RED = " DELETE_CART_RED"